defaults:
    kick-message: Du wurdest gekickt, probiere es wieder in 5 Sekunden.
    delay: true
    time: 5
    warning-message: Lockdown wurde aktiviert!
    warning-prefix: WARNUNGG
    motd: true
    persist: true
    motd-message: LockDown aktiviert!
    auto-update: true
broadcasts:
    enable: true
    disable: true
    warning: true
ld: false
