name: LockDown
main: me.zertixmx.lockdown.LockDown
version: 1.5.9
author: zertixmx
website: LabGaming.tk
commands:
    ld:
      description: LockDown Cmds
      usage: /ld [enable,disable,info,help,reload,status]
permissions:
    ld.toggle:
        description: Berechting fürs togglen von Lockdown.
    ld.urgent:
        description: Berechting für schedule an urgent lockdown
    ld.help: 
        description: Berechting für die Hilfe Nachricht
    ld.reload:
        description: Berechting fürs reloaden des Plugins
    ld.bypass:
        description: Berechting fürs joinen bei aktivierten LockDown
    ld.status:
        description: Berechting zum den Lockdown Status zu checken
    ld.info:
        description: Berechting für die Plugin Info
    ld.*:
        description: All LockDown permissions
        children:
            ld.bypass: true
            ld.toggle: true
            ld.instant: true
            ld.reload: true
            ld.status: true
            ld.help: true
            ld.info: true
